### ISSUE TITLE
sigmoid层

### ISSUE THREAD

**Issue by Aqi-MH13** [bugsuse/weather4cast-2022-stage2#1]
您好，在您的论文中提到使用sigmoid层将模型输出范围设置在 0 到 1，我想问一下sigmoid层在什么地方修改的，希望能得到您的回复。

**Comment by bugsuse** [comment]
sigmoid放在了模型的最后，具体设置如下：

https://github.com/bugsuse/weather4cast-2022-stage2/blob/ff9ff4768ca9a37716514db593a1dd4f56d585ff/models/trainer.py#L94-L95
